name: helloworld
on: push
jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Do helloworld
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: |
            do hello --log-format plain